name: .NET Core CI

on:
  push:
    branches:
      - '*'

env:
  BUILDEVENT_APIKEY: ${{ secrets.HONEYCOMB_APIKEY }}

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - run: export BUILD_START=$(date +%s)
      if: runner.os == 'Linux'
    - uses: actions/setup-go@v2
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install buildevents
      run: go get github.com/bgrainger/buildevents/
    - name: .NET Restore
      run: |
        STEP_START=$(date +%s)
        /home/runner/go/bin/buildevents cmd ${{ github.repository }}:${{ github.run_id }} ${{ github.action }} build -- dotnet restore
        /home/runner/go/bin/buildevents step ${{ github.repository }}:${{ github.run_id }} ${{ github.action }} $STEP_START build
    - name: .NET Build
      run: |
        STEP_START=$(date +%s)
        /home/runner/go/bin/buildevents cmd ${{ github.repository }}:${{ github.run_id }} ${{ github.action }} restore -- dotnet build --configuration Release --no-restore
        /home/runner/go/bin/buildevents step ${{ github.repository }}:${{ github.run_id }} ${{ github.action }} $STEP_START restore
    - name: Finish build
      run: |
        /home/runner/go/bin/buildevents build ${{ github.repository }}:${{ github.run_id }} ${{ env.BUILD_START }} success
